namespace :rabbitmq do
  desc "Setup routing"
  task :setup do
    require "bunny"

    conn = Bunny.new
    conn.start

    ch = conn.create_channel

    # get or create exchange
    x = ch.fanout("ninebeike.new_member")

    # get or create queue (note the durable setting)
    queue = ch.queue("ninebeike.new_member", durable: true)

    # bind queue to exchange
    queue.bind("ninebeike.new_member")

    conn.close
  end
end